"""Core domain models and schemas for the ATLAS platform.

This package exposes the complete, technology-independent domain language
of the project. No business logic, persistence, or infrastructure concerns
are contained here.
"""

from engine.domain.architecture import (
    ArchitecturalDecision,
    Architecture,
    ArchitectureComponent,
    ArchitectureDriver,
    ArchitectureSnapshot,
    ArchitectureSummary,
    InterfaceContract,
    QualityAttribute,
    Risk,
    Constraint as ArchitectureConstraint,
    Assumption as ArchitectureAssumption,
)
from engine.domain.ai import (
    AIToolSchema,
    AIGenerationParameters,
    ProviderCapabilities,
    ContextPayload,
    AIRequest,
    AIResponse,
    PromptTemplateMetadata,
    AIProposal,
)
from engine.domain.conversation import (
    ConversationMessage,
    ConversationSession,
    MemoryCandidate,
)
from engine.domain.engineering_specification import EngineeringSpecification
from engine.domain.enums import (
    ArchitectureStatus,
    ConversationRole,
    EvaluationStatus,
    FindingSeverity,
    FindingCategory,
    FindingLifecycleStatus,
    PlanningStatus,
    ProposalStatus,
    ProposalType,
    Priority,
    ProjectStatus,
    ResearchStatus,
    TaskStatus,
    WorkflowStage,
)
from engine.domain.evaluation import (
    Evaluation,
    EvaluationFinding,
    EvaluationSnapshot,
    EvaluationSummary,
    ReadinessDecision,
    RequirementCoverage,
)
from engine.domain.memory import Memory, MemoryEntry
from engine.domain.metadata import ArtifactMetadata, ArtifactStatus
from engine.domain.planning import (
    AcceptanceCriteria,
    DefinitionOfDone,
    EngineeringDeliverable,
    Planning,
    PlanningEpic,
    PlanningMilestone,
    PlanningSnapshot,
    PlanningSubtask,
    PlanningSummary,
    PlanningTask,
    ScopeDefinition,
)
from engine.domain.project import Project
from engine.domain.research import (
    Assumption,
    Constraint,
    Evidence,
    Opportunity,
    ProblemDefinition,
    Research,
    ResearchFinding,
    ResearchSnapshot,
    ResearchSource,
    ResearchSummary,
)
from engine.domain.review import EngineeringReview
from engine.domain.traceability import TraceabilityLink
from engine.domain.workflow import ReadinessReview, Workflow, WorkflowHistoryEntry
from engine.domain.workspace import Workspace, WorkspaceArtifact

__all__ = [
    "AcceptanceCriteria",
    "ArchitecturalDecision",
    "Architecture",
    "ArchitectureComponent",
    "ArchitectureDriver",
    "ArchitectureSnapshot",
    "ArchitectureStatus",
    "ArchitectureSummary",
    "ArtifactMetadata",
    "ArtifactStatus",
    "AIToolSchema",
    "AIGenerationParameters",
    "ProviderCapabilities",
    "ContextPayload",
    "AIRequest",
    "AIResponse",
    "PromptTemplateMetadata",
    "AIProposal",
    "ConversationMessage",
    "ConversationRole",
    "ConversationSession",
    "Assumption",
    "Constraint",
    "ArchitectureConstraint",
    "ArchitectureAssumption",
    "DefinitionOfDone",
    "EngineeringDeliverable",
    "EngineeringReview",
    "EngineeringSpecification",
    "Evaluation",
    "EvaluationFinding",
    "EvaluationSnapshot",
    "EvaluationStatus",
    "EvaluationSummary",
    "Evidence",
    "FindingSeverity",
    "FindingCategory",
    "FindingLifecycleStatus",
    "InterfaceContract",
    "Memory",
    "MemoryCandidate",
    "MemoryEntry",
    "Opportunity",
    "Planning",
    "PlanningEpic",
    "PlanningMilestone",
    "PlanningSnapshot",
    "PlanningStatus",
    "PlanningSubtask",
    "PlanningSummary",
    "PlanningTask",
    "Priority",
    "ProblemDefinition",
    "Project",
    "ProjectStatus",
    "ProposalStatus",
    "ProposalType",
    "QualityAttribute",
    "ReadinessDecision",
    "RequirementCoverage",
    "Research",
    "ResearchFinding",
    "ResearchSnapshot",
    "ResearchSource",
    "ResearchStatus",
    "ResearchSummary",
    "Risk",
    "ReadinessReview",
    "ScopeDefinition",
    "TaskStatus",
    "TraceabilityLink",
    "Workflow",
    "WorkflowHistoryEntry",
    "WorkflowStage",
    "Workspace",
    "WorkspaceArtifact",
]
